import 'package:company_one_plus/models/models.dart';

var db = {
  'C': [
    'بامي',
    'سبيناغ',
    'طماطا',
    'قرنابيط',
    'ثوم',
    ' المعمر',
    'سلج',
    'الجرجير',
    'الفجل',
    'الخس',
    'لهانه الحمره',
    'الشوندر',
    ' البطيخ',
    'ملفوف اخضر',
    'الجرجير',
    'الفجل',
    'الخس',
    'لهانه الحمره'
  ],
};
// ignore: non_constant_identifier_names
final vitamin_A = <Vitamin>[
  Vitamin(food: 'بامي', vitamin: 'vitamin A'),
  Vitamin(food: 'بطاطا', vitamin: 'vitamin A'),
  Vitamin(food: 'الحلو', vitamin: 'vitamin A'),
  Vitamin(food: 'سبيناغ', vitamin: 'vitamin A'),
  Vitamin(food: 'طماطا', vitamin: 'vitamin A'),
  Vitamin(food: 'حمص', vitamin: 'vitamin A'),
  Vitamin(food: 'بزاليا', vitamin: 'vitamin A'),
  Vitamin(food: 'ثوم', vitamin: 'vitamin A'),
  Vitamin(food: 'المعمر', vitamin: 'vitamin A'),
  Vitamin(food: 'رز', vitamin: 'vitamin A'),
  Vitamin(food: 'سلج', vitamin: 'vitamin A'),
  Vitamin(food: 'جرجير', vitamin: 'vitamin A'),
  Vitamin(food: 'الخس', vitamin: 'vitamin A'),
  Vitamin(food: 'لهانه الحمره', vitamin: 'vitamin A'),
  Vitamin(food: 'البطيخ', vitamin: 'vitamin A'),
  Vitamin(food: 'وفلفل', vitamin: 'vitamin A'),
  Vitamin(food: 'كراث', vitamin: 'vitamin A'),
  Vitamin(food: 'بصل', vitamin: 'vitamin A'),
  Vitamin(food: 'اخضر', vitamin: 'vitamin A'),
  Vitamin(food: 'جزر', vitamin: 'vitamin A'),
  Vitamin(food: 'يقطين', vitamin: 'vitamin A'),
  Vitamin(food: 'فاصوليا', vitamin: 'vitamin A'),
  Vitamin(food: 'عدس', vitamin: 'vitamin A'),
  Vitamin(food: 'خيار', vitamin: 'vitamin A'),
  Vitamin(food: 'التفاح', vitamin: 'vitamin A'),
  Vitamin(food: 'المانجو', vitamin: 'vitamin A'),
  Vitamin(food: 'الكرفس', vitamin: 'vitamin A'),
];

final vitamin_C = <Vitamin>[
  Vitamin(food: 'بامي', vitamin: 'vitamin C'),
  Vitamin(food: 'سبيناغ', vitamin: 'vitamin C'),
  Vitamin(food: 'طماطا', vitamin: 'vitamin C'),
  Vitamin(food: 'قرنابيط', vitamin: 'vitamin C'),
  Vitamin(food: 'ثوم', vitamin: 'vitamin C'),
  Vitamin(food: 'المعمر', vitamin: 'vitamin C'),
  Vitamin(food: 'سلج', vitamin: 'vitamin C'),
  Vitamin(food: 'الجرجير', vitamin: 'vitamin C'),
  Vitamin(food: 'الفجل', vitamin: 'vitamin C'),
  Vitamin(food: 'الخس', vitamin: 'vitamin C'),
  Vitamin(food: 'لهانه الحمره', vitamin: 'vitamin C'),
  Vitamin(food: 'الشوندر', vitamin: 'vitamin C'),
  Vitamin(food: 'البطيخ', vitamin: 'vitamin C'),
  Vitamin(food: 'ملفوف اخضر', vitamin: 'vitamin C'),
  Vitamin(food: 'الجرجير', vitamin: 'vitamin C'),
  Vitamin(food: 'الفجل', vitamin: 'vitamin C'),
];
